apiVersion: v1 
kind: ConfigMap 
metadata:
  name: backend
  namespace: expense
data:
  DB_Host: mysql #mysql component service name
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backend
  namespace: expense 
  labels: 
    component: backend 
    project: expense 
    tier: db
spec:
  replicas: 2 
  selector:
    matchLabels:
      component: backend 
      project: expense 
      tier: db
  template:
    metadata:
      labels: 
        component: backend 
        project: expense 
        tier: db
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup myservice; do echo waiting for myservice; sleep 2; done"] 
      containers:
      - name: backend
        image: joindevops/backend:v1.0
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        envFrom:
        - configMapRef:
            name: backend
---
apiVersion: v1 
kind: Service 
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend 
    project: expense 
    tier: db
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port



  